### ISSUE TITLE
PDF Issues Recently

### ISSUE THREAD

**Issue by F1nny** [geobarrod/KDE-Services#1]
Hey guys, firstly thanks for this amazing project :) Been using for a longggg time and love it! Anyway at some point in the past couple months maximum (believe closer to 1 month) the PDF tools completely stopped working, I know it had nothing to do with your package and more likely the latest KDE updates but wondering if have any idea. I have all the tools necessary as that hasn't changed, but using PDF Compress for example does nothing - at one point I saw an error pop up saying something about cannot find command "%F -" or something of that sort, variable F and a hyphen but didn't get to catch it. I upgraded to the latest kde-services and still no luck/not seeing error anymore but still not doing anything. Any ideas appreciated!

Arch Linux x64
Latest KDE looks to have broken it some point in past month

/edit One thing I did remove recently was poppler-qt4 (still have -qt5, poppler-glib, etc.) as it was reported as unnecessary, however I did try reinstalling it with poppler-data and still having same issue. Another large upgrade recently was the xorg server to 1.19, any ideas appreciated:)

**Comment by cFINNY** [comment]
Tracked it down and looks like the PDFktools.sh script somehow lost it's executable bit, added that and all looks good now!

**Comment by tuxflo** [comment]
That issue should not set to closed, since it is still valid. Tested on manjaro Linux (KDE flavour) and KDE neon.
Readding the executable bit works on both systems, maybe a missconfiguration in the Makefile?

**Comment by geobarrod** [comment]
The Makefile only install and uninstall

**Comment by F1nny** [comment]
Very weird, yea my bad for closing just thought it was a local issue as couldn't find any other reports! Definitely weird in any case, any ideas as to the root cause?
