### ISSUE TITLE
Checksums are not appearing

### ISSUE THREAD

**Issue by bjmuld** [geobarrod/KDE-Services#10]
I get a notification when computation is complete, but I do not see anywhere where the checksum digest is reported...

I'm in KDE Neon (Ubuntu 20.04 + Plasma 5.22.1)

**Comment by geobarrod** [comment]
Please send me a short video in mp4 format (h264 or h265) or GIF showing the problem to kde.services.23.11.2011@gmail.com

**Comment by bjmuld** [comment]
Sorry.  After a reboot, I see that files are being created.
