### ISSUE TITLE
zh_cn translation is too hard to understand

### ISSUE THREAD

**Issue by BruceZhang1993** [geobarrod/KDE-Services#2]
I can hardly understand the meaning of the dolphin context menu services.

Maybe a PR to improve chinese translation ?

**Comment by geobarrod** [comment]
Sorry, my native language is Spanish and I only know English at a technical level used in systems and networks administration for servers and computers. The translation into several languages I did it with translation software, knew that would not be correct but I had a hunch that would collaborate users. Could you collaborate with the translation to [zh_cn]?

**Comment by BruceZhang1993** [comment]
@geobarrod Sure, I'd like to contribute to zh-cn translation. Fork this repo & make a pr. Is it right?

**Comment by BruceZhang1993** [comment]
#3 
just fixed zh-cn translations

**Comment by geobarrod** [comment]
Let me know if you want to be added to the list of contributors, if so, send me your name and email. Thank you very much for your contribution.

**Comment by BruceZhang1993** [comment]
@geobarrod sure, i'd like to.
English name is Bruce Zhang Email zttt183525594@gmail.com
one more suggestion, will you add multi lang support for these scripts?

**Comment by geobarrod** [comment]
Ok, on the next release, you'll be on the contributors list.
Adding support for multi language in scripts is an arduous task for which I need time, which at the moment is impossible for my work, but it is in my plans to do it. In the future you can send me any suggestions or bug reports to kde.services.23.11.2011@gmail.com
I reiterate my appreciation for your contribution.
