### ISSUE TITLE
Compatibility with Debian?

### ISSUE THREAD

**Issue by Fabian42** [geobarrod/KDE-Services#6]
I tried to install this and had some problems that you can read about here:https://unix.stackexchange.com/questions/457310/kde-services-dependencies/457357?noredirect=1#comment831019_457357

Wikipedia does not list Debian as a "RedHat based OS", but this program is listed in the extension manager of Dolphin. So is it compatible or not? And what do I have to do to install it?

**Comment by geobarrod** [comment]
Hello,

KDE-Services can be installed from your Tarball (kde-services-3.0.2.tar.bz2) in any Unix-like distro, if all the required dependencies described in the following link are installed:

https://store.kde.org/p/998464/

However, where it works correctly is in distros based on RedHat OS. I developed and adjusted the code to the Fedora distro, which I strongly recommend.

I hope you enjoy it.
Have a nice day.

**Comment by Fabian42** [comment]
But I can't install it, because for example it depends on "transcode", of which I can only find versions that rely explicitly on older versions of its dependencies than what I can install. For example it depends on libmagickcore-6.q16-2, which depends on a version of imagemagick-common that is older than the one I have installed. And even if I delete the newer version (apart from breaking other programs), I still can't install the older version, because it automatically detects that a newer version is available and installs that instead. Which breaks libmagickcore-6.q16-2 again. So how do I install all dependencies for this program?

**Comment by Fabian42** [comment]
Why is this closed? Nobody ever answered my question!

**Comment by geobarrod** [comment]
It is not possible to solve dependency problems for each particular distro. I reiterate what I said in my previous response:

... the services menu work ... in distros based on RedHat OS. I developed and adjusted the code to the Fedora distro, which I strongly recommend.

Sorry. Have a nice day!

**Comment by Fabian42** [comment]
So it's not compatible with Debian? Then it shouldn't appear in that menu.

**Comment by geobarrod** [comment]
It is compatible with any unix-like distro depending on the number of dependent packages that can be installed. Install only the dependencies that do not give problems and use only the menu services that do not need problematic dependencies. Disable all incompatible menu services.

**Comment by Fabian42** [comment]
Not sure what you're trying to tell me, but I was saying that something that isn't compatible with Debian should not appear in a software list in a program running on Debian.
