### ISSUE TITLE
Android Tools not showing up

### ISSUE THREAD

**Issue by kinoegit** [geobarrod/KDE-Services#8]
Great work! Thank you so much!!
My issue: submenu "Android Tools" should be shown when clicked a directory - but it is not, wether Android device is plugged in or not.
Til now i haven't seen it except when clicking /usr/share/kservices5/ServiceMenus/Android-Tools_servicemenu.desktop. The latter seems to be correct.
What am i missing? Or is it a bug?

Version: 3.0.2-2
Operating System: Arch Linux 
KDE Plasma Version: 5.15.3
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.2

**Comment by kinoegit** [comment]
For some inexplicable reason, only Android tools in the Dolphin Settings services was unchecked by default, all other KDE services were checked--- a bit embarrassing.
Issue solved

**Comment by geobarrod** [comment]
Hi, forgive the delay in my answer and even more after you find the solution. I have so much work to do in my job. I was doing a little research on the source code and did not see any option that by default disable that menu service. Thank you very much for reporting your issue and the solution. I hope that KDE-Services will be useful for you. Enjoy it and share it. Have a nice day.
